### ISSUE TITLE
System is not ready: Platform Windows is not supported

### ISSUE THREAD

**Issue by dragokas** [iyulab/FastFind.NET#6]
Even if I try to bypass this memory bug: https://github.com/iyulab/FastFind.NET/issues/1

When using the provided NuGet package, the following error occured:
```
System is not ready: Platform Windows is not supported
```

Steps to reproduce:
1. Create console NET 10 project.
2. Install NuGet package "FastFind.Windows"
3. Run the code:
```
using FastFind;

class Program
{
    public static async Task Main()
    {
        await SearchSimple();
    }

    public static async Task SearchSimple()
    {
        SystemValidationResult? validation;

        {
            // Temporarily increase WorkingSet to bypass FastFind.NET startup bug
            int items = 4 * 1024 * 1024;
            List<string> list = new();
            for (int i = 0; i < items; i++)
            {
                list.Add(i.ToString());
            }

            // Validate system and create search engine
            validation = FastFinder.ValidateSystem();
        }

        Console.WriteLine($"✅ {validation.GetSummary()}");

        if (validation.IsReady)
        {
            // Windows-specific factory method available
            var searchEngine = FastFinder.CreateWindowsSearchEngine();
        }
    }
}
```
With the appropriate exception if you try to call CreateWindowsSearchEngine() ignoring the ready state:
```
System.PlatformNotSupportedException: No search engine implementation available for platform: Windows
```

Environment:
Windows 11, MS VS 2026.

**Comment by iyulab-caveman** [comment]
Closed: Fixed in v1.0.10 - ModuleInitializer now auto-registers Windows factory on assembly load

**Comment by dragokas** [comment]
New NuGet package version 1.0.10 not fixed this issue.

However, calling: 
```
WindowsRegistration.EnsureRegistered();
```
manually did the job.
